- id: nbstripout
  name: Strip Outputs from Notebooks
  description: Strip outputs from all new notebooks
  entry: nbstripout
  language: script
  files: (^|/).+\.ipynb$

- id: validate_secrets_are_encrypted
  name: Check that secret files are formatted correctly
  description: Check Kubernetes Secret are Encrypted with SOPS
  entry: validate_secrets_are_encrypted
  language: python
  types: [yaml]

- id: validate_encrypted_secret_name
  name: Check secret files for correct ending
  description: Check SOPS Encrypted Secrets' File Names End with .enc.yaml
  entry: validate_encrypted_secret_name
  language: python
  types: [yaml]
