- id: nbstripout
  name: Strip Outputs from Notebooks
  description: Strip outputs from all new notebooks
  entry: nbstripout
  language: script
  types: [jupyter]

- id: validate_secrets_are_encrypted
  name: Check Kubernetes' Secrets are Encrypted with SOPS
  description: Check kubernetes' secrets are encrypted with SOPS
  entry: validate_secrets_are_encrypted
  language: python
  types: [yaml]

- id: validate_encrypted_secret_name
  name: Check Kubernetes SOPS Encrypted Secrets' Filenames End with .enc.yaml
  description: Check kubernetes' SOPS encrypted yaml secrets` filenames end with .enc.yaml
  entry: validate_encrypted_secret_name
  language: python
  types: [yaml]

- id: check_notebook_has_parameters_cell
  name: Check that all notebooks contain a cell tagged with 'parameters'
  description: Check that all notebooks contain a cell tagged with 'parameters'
  entry: check_notebook_has_parameters_cell
  language: python
  types: [jupyter]

- id: nbsmoke_lint
  name: Check that all notebooks pass nbsmoke lint check
  description: Check that all notebooks pass nbsmoke lint check
  entry: nbsmoke_lint
  language: python
  types: [jupyter]

- id: pg_format
  name: Format postgres SQL files with pgFormatter
  description: Format postgres SQL files with pgFormatter
  entry: pgFormatter/pg_format -i -L
  language: script
  types: [sql]
